CREATE TABLE HRMS.BRANCH_DEPO
(
  ID              NUMBER,
  CODE            VARCHAR2(5 BYTE),
  NAME            VARCHAR2(50 BYTE),
  ADDRESS         VARCHAR2(100 BYTE),
  CONTACT_PERSON  NUMBER,
  PHONE           VARCHAR2(30 BYTE),
  EMAIL           VARCHAR2(30 BYTE),
  ENT_BY          NUMBER,
  ENT_DATE        DATE,
  UPD_BY          NUMBER,
  UPD_DATE        DATE
);
/

ALTER TABLE HRMS.BRANCH_DEPO ADD (
  CONSTRAINT BR_DEPOTS_PK
  PRIMARY KEY
  (ID)
,  CONSTRAINT BR_DEPOTS_U01
  UNIQUE (CODE));


CREATE TABLE HRMS.COMPANY
(
  ID        NUMBER,
  CODE      VARCHAR2(5 BYTE),
  NAME      VARCHAR2(50 BYTE),
  ADDRESS   VARCHAR2(100 BYTE),
  REG_NO    VARCHAR2(30 BYTE),
  BIN       VARCHAR2(30 BYTE),
  PHONE     VARCHAR2(30 BYTE),
  EMAIL     VARCHAR2(30 BYTE),
  ENT_BY    NUMBER,
  ENT_DATE  DATE,
  UPD_BY    NUMBER,
  UPD_DATE  DATE
);


CREATE UNIQUE INDEX HRMS.COMPANY_PK ON HRMS.COMPANY
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
CREATE UNIQUE INDEX HRMS.COMPANY_U01 ON HRMS.COMPANY
(CODE)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
CREATE UNIQUE INDEX HRMS.COMPANY_U02 ON HRMS.COMPANY
(BIN)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.COMPANY ADD (
  CONSTRAINT COMPANY_PK
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.COMPANY_PK
  ENABLE VALIDATE
,  CONSTRAINT COMPANY_U01
  UNIQUE (CODE)
  USING INDEX HRMS.COMPANY_U01
  ENABLE VALIDATE
,  CONSTRAINT COMPANY_U02
  UNIQUE (BIN)
  USING INDEX HRMS.COMPANY_U02
  ENABLE VALIDATE);


DROP TABLE HRMS.DEPT CASCADE CONSTRAINTS;

CREATE TABLE HRMS.DEPT
(
  DEPTNO  NUMBER(2),
  DNAME   VARCHAR2(14 BYTE),
  LOC     VARCHAR2(13 BYTE)
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


ALTER TABLE HRMS.DEPT ADD (
  PRIMARY KEY
  (DEPTNO)
  USING INDEX
    TABLESPACE HRMS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);


DROP TABLE HRMS.DESIGNATIONS CASCADE CONSTRAINTS;

CREATE TABLE HRMS.DESIGNATIONS
(
  ID           NUMBER,
  REFNO        VARCHAR2(30 BYTE),
  REFDATE      DATE,
  CODE         VARCHAR2(30 BYTE),
  DESIGNATION  VARCHAR2(100 BYTE),
  ENT_BY       NUMBER,
  ENT_DATE     DATE,
  UPD_BY       NUMBER,
  UPD_DATE     DATE
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.DESIGNATIONS_PK ON HRMS.DESIGNATIONS
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.DESIGNATIONS ADD (
  CONSTRAINT DESIGNATIONS_PK
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.DESIGNATIONS_PK
  ENABLE VALIDATE);


DROP TABLE HRMS.EMP CASCADE CONSTRAINTS;

CREATE TABLE HRMS.EMP
(
  EMPNO     NUMBER(4)                           NOT NULL,
  ENAME     VARCHAR2(10 BYTE),
  JOB       VARCHAR2(9 BYTE),
  MGR       NUMBER(4),
  HIREDATE  DATE,
  SAL       NUMBER(7,2),
  COMM      NUMBER(7,2),
  DEPTNO    NUMBER(2)
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


ALTER TABLE HRMS.EMP ADD (
  PRIMARY KEY
  (EMPNO)
  USING INDEX
    TABLESPACE HRMS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);


DROP TABLE HRMS.EMPLOYEES CASCADE CONSTRAINTS;

CREATE TABLE HRMS.EMPLOYEES
(
  ID              NUMBER,
  EMP_ID          VARCHAR2(30 BYTE),
  F_NAME          VARCHAR2(30 BYTE),
  L_NAME          VARCHAR2(30 BYTE),
  DOB             DATE,
  MOBILE          VARCHAR2(30 BYTE),
  EMAIL           VARCHAR2(30 BYTE),
  FATHER          VARCHAR2(50 BYTE),
  MOTHER          VARCHAR2(50 BYTE),
  GENDER          VARCHAR2(10 BYTE),
  HEIGHT          VARCHAR2(10 BYTE),
  WEIGHT          VARCHAR2(10 BYTE),
  BLOOD           VARCHAR2(10 BYTE),
  NID             VARCHAR2(30 BYTE),
  ADDRESS         VARCHAR2(30 BYTE),
  C_POST          NUMBER,
  C_THANA         NUMBER,
  C_DISTRICT      NUMBER,
  C_DIVISION      NUMBER,
  P_ADDRESS       VARCHAR2(30 BYTE),
  P_POST          NUMBER,
  P_THANA         NUMBER,
  P_DISTRICT      NUMBER,
  P_DIVISION      NUMBER,
  PHOTO           BLOB,
  JOIN_DATE       DATE,
  MARITAL_STATUS  VARCHAR2(10 BYTE),
  EMP_TYPE        VARCHAR2(30 BYTE),
  DEPT_ID         NUMBER,
  LOC_ID          NUMBER,
  BRANCH_ID       NUMBER,
  DESIG_ID        NUMBER,
  COM_ID          NUMBER,
  JOB_ID          NUMBER,
  USER_GRP        NUMBER(3)                     DEFAULT 0,
  PASSW           VARCHAR2(32 BYTE),
  ENT_BY          NUMBER,
  ENT_DATE        DATE,
  UPD_BY          NUMBER,
  UPD_DATE        DATE,
  STATUS          VARCHAR2(10 BYTE)
)
LOB (PHOTO) STORE AS SECUREFILE (
  TABLESPACE  HRMS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.EMPLOYESS_U01 ON HRMS.EMPLOYEES
(EMP_ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
CREATE UNIQUE INDEX HRMS.EMPLOYESS_U02 ON HRMS.EMPLOYEES
(EMAIL)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
CREATE UNIQUE INDEX HRMS.EMPLOYESS_U03 ON HRMS.EMPLOYEES
(NID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
CREATE UNIQUE INDEX HRMS.PK_EMPLOYESS ON HRMS.EMPLOYEES
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.EMPLOYEES ADD (
  CONSTRAINT PK_EMPLOYESS
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.PK_EMPLOYESS
  ENABLE VALIDATE
,  CONSTRAINT EMPLOYESS_U01
  UNIQUE (EMP_ID)
  USING INDEX HRMS.EMPLOYESS_U01
  ENABLE VALIDATE
,  CONSTRAINT EMPLOYESS_U02
  UNIQUE (EMAIL)
  USING INDEX HRMS.EMPLOYESS_U02
  ENABLE VALIDATE
,  CONSTRAINT EMPLOYESS_U03
  UNIQUE (NID)
  USING INDEX HRMS.EMPLOYESS_U03
  ENABLE VALIDATE);


DROP TABLE HRMS.EMP_EDUCATION CASCADE CONSTRAINTS;

CREATE TABLE HRMS.EMP_EDUCATION
(
  ID            NUMBER,
  EMP_ID        NUMBER,
  EXAM          VARCHAR2(100 BYTE),
  PASSING_YEAR  NUMBER(4),
  BOARD         VARCHAR2(100 BYTE),
  CGPA          NUMBER(5,2),
  REMARKS       VARCHAR2(100 BYTE),
  ENT_BY        NUMBER,
  ENT_DATE      DATE,
  UPD_BY        NUMBER,
  UPD_DATE      DATE
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.PK_EMP_EDUCATION ON HRMS.EMP_EDUCATION
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.EMP_EDUCATION ADD (
  CONSTRAINT PK_EMP_EDUCATION
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.PK_EMP_EDUCATION
  ENABLE VALIDATE);


DROP TABLE HRMS.EMP_EXPERIENCE CASCADE CONSTRAINTS;

CREATE TABLE HRMS.EMP_EXPERIENCE
(
  ID            NUMBER,
  EMP_ID        NUMBER,
  COMPANY_NAME  VARCHAR2(100 BYTE),
  JOB_TITLE     VARCHAR2(100 BYTE),
  JOB_DES       VARCHAR2(100 BYTE),
  START_DATE    DATE,
  END_DATE      DATE,
  DURATION      VARCHAR2(100 BYTE),
  REMARKS       VARCHAR2(100 BYTE),
  ENT_BY        NUMBER,
  ENT_DATE      DATE,
  UPD_BY        NUMBER,
  UPD_DATE      DATE
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.PK_EMP_ID_EXPERIENCE ON HRMS.EMP_EXPERIENCE
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.EMP_EXPERIENCE ADD (
  CONSTRAINT PK_EMP_ID_EXPERIENCE
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.PK_EMP_ID_EXPERIENCE
  ENABLE VALIDATE);


DROP TABLE HRMS.EMP_FAMILY_DTL CASCADE CONSTRAINTS;

CREATE TABLE HRMS.EMP_FAMILY_DTL
(
  ID        NUMBER,
  EMP_ID    NUMBER,
  RELATION  VARCHAR2(100 BYTE),
  NAME      VARCHAR2(100 BYTE),
  AGE       NUMBER,
  REMARKS   VARCHAR2(100 BYTE),
  ENT_BY    NUMBER,
  ENT_DATE  DATE,
  UPD_BY    NUMBER,
  UPD_DATE  DATE
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.PK_EMP_FAMILY_DTL ON HRMS.EMP_FAMILY_DTL
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.EMP_FAMILY_DTL ADD (
  CONSTRAINT PK_EMP_FAMILY_DTL
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.PK_EMP_FAMILY_DTL
  ENABLE VALIDATE);


DROP TABLE HRMS.EMP_GUARANTORS CASCADE CONSTRAINTS;

CREATE TABLE HRMS.EMP_GUARANTORS
(
  ID               NUMBER,
  EMP_ID           NUMBER,
  NAME             VARCHAR2(100 BYTE),
  RELATIONSHIP     VARCHAR2(100 BYTE),
  CONTACT_DETAILS  VARCHAR2(255 BYTE),
  ADDRESS          VARCHAR2(100 BYTE),
  P_POST           NUMBER,
  P_THANA          NUMBER,
  P_DISTRICT       NUMBER,
  P_DIVISION       NUMBER,
  REMARKS          VARCHAR2(100 BYTE),
  ENT_BY           NUMBER,
  ENT_DATE         DATE,
  UPD_BY           NUMBER,
  UPD_DATE         DATE
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.PK_EMP_ID_GUARANTORS ON HRMS.EMP_GUARANTORS
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.EMP_GUARANTORS ADD (
  CONSTRAINT PK_EMP_ID_GUARANTORS
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.PK_EMP_ID_GUARANTORS
  ENABLE VALIDATE);


DROP TABLE HRMS.EMP_NOMINEE CASCADE CONSTRAINTS;

CREATE TABLE HRMS.EMP_NOMINEE
(
  ID               NUMBER,
  EMP_ID           NUMBER,
  NOMINEE_NAME     VARCHAR2(100 BYTE),
  RELATIONSHIP     VARCHAR2(100 BYTE),
  CONTACT_DETAILS  VARCHAR2(255 BYTE),
  ADDRESS          VARCHAR2(100 BYTE),
  P_POST           NUMBER,
  P_THANA          NUMBER,
  P_DISTRICT       NUMBER,
  P_DIVISION       NUMBER,
  REMARKS          VARCHAR2(100 BYTE),
  ENT_BY           NUMBER,
  ENT_DATE         DATE,
  UPD_BY           NUMBER,
  UPD_DATE         DATE
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.PK_EMP_NOMINEE ON HRMS.EMP_NOMINEE
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.EMP_NOMINEE ADD (
  CONSTRAINT PK_EMP_NOMINEE
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.PK_EMP_NOMINEE
  ENABLE VALIDATE);


DROP TABLE HRMS.EMP_TRAINING CASCADE CONSTRAINTS;

CREATE TABLE HRMS.EMP_TRAINING
(
  ID               NUMBER,
  EMP_ID           NUMBER,
  TRAINING_NAME    VARCHAR2(100 BYTE),
  INSTITUTION      VARCHAR2(100 BYTE),
  START_DATE       DATE,
  COMPLETION_DATE  DATE,
  DURATION         VARCHAR2(100 BYTE),
  REMARKS          VARCHAR2(100 BYTE),
  ENT_BY           NUMBER,
  ENT_DATE         DATE,
  UPD_BY           NUMBER,
  UPD_DATE         DATE
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.PK_EMP_TRAINING ON HRMS.EMP_TRAINING
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.EMP_TRAINING ADD (
  CONSTRAINT PK_EMP_TRAINING
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.PK_EMP_TRAINING
  ENABLE VALIDATE);


DROP TABLE HRMS.LOCATIONS CASCADE CONSTRAINTS;

CREATE TABLE HRMS.LOCATIONS
(
  ID        NUMBER,
  NAME      VARCHAR2(50 BYTE),
  ADDRESS   VARCHAR2(100 BYTE),
  PHONE     VARCHAR2(30 BYTE),
  EMAIL     VARCHAR2(30 BYTE),
  COM_ID    NUMBER,
  ENT_BY    NUMBER,
  ENT_DATE  DATE,
  UPD_BY    NUMBER,
  UPD_DATE  DATE
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.LOCATIONS_PK ON HRMS.LOCATIONS
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.LOCATIONS ADD (
  CONSTRAINT LOCATIONS_PK
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.LOCATIONS_PK
  ENABLE VALIDATE);


DROP TABLE HRMS.T_MENU CASCADE CONSTRAINTS;

CREATE TABLE HRMS.T_MENU
(
  PID               NUMBER                      NOT NULL,
  PARENT_PID        NUMBER,
  MENU_NAME         NVARCHAR2(100),
  MENU_LINK         NVARCHAR2(200),
  STATUS            NVARCHAR2(1),
  DESCRIPTION       NVARCHAR2(200),
  SORT_BY           NUMBER,
  ENT_BY            NUMBER,
  UPD_BY            NUMBER,
  ENT_DATE          DATE                        DEFAULT SYSDATE,
  UPD_DATE          DATE,
  ICON_IMG          VARCHAR2(250 BYTE),
  MENU_NAME_BANGLA  VARCHAR2(250 BYTE)
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.T_MENU_CON_PK ON HRMS.T_MENU
(PID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.T_MENU ADD (
  CONSTRAINT T_MENU_C01
  CHECK (parent_pid <> pid)
  ENABLE VALIDATE
,  CONSTRAINT T_MENU_CON_PK
  PRIMARY KEY
  (PID)
  USING INDEX HRMS.T_MENU_CON_PK
  ENABLE VALIDATE);


DROP TABLE HRMS.T_STATUS CASCADE CONSTRAINTS;

CREATE TABLE HRMS.T_STATUS
(
  ID      NUMBER(1),
  STATUS  VARCHAR2(30 BYTE)
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.T_STATUS_PK ON HRMS.T_STATUS
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.T_STATUS ADD (
  CONSTRAINT T_STATUS_PK
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.T_STATUS_PK
  ENABLE VALIDATE);


DROP TABLE HRMS.UNITS CASCADE CONSTRAINTS;

CREATE TABLE HRMS.UNITS
(
  ID        NUMBER,
  NAME      VARCHAR2(50 BYTE),
  ADDRESS   VARCHAR2(100 BYTE),
  PHONE     VARCHAR2(30 BYTE),
  EMAIL     VARCHAR2(30 BYTE),
  COM_ID    NUMBER,
  ENT_BY    NUMBER,
  ENT_DATE  DATE,
  UPD_BY    NUMBER,
  UPD_DATE  DATE
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.UNITS_PK ON HRMS.UNITS
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.UNITS ADD (
  CONSTRAINT UNITS_PK
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.UNITS_PK
  ENABLE VALIDATE);


DROP TABLE HRMS.USER_GROUP CASCADE CONSTRAINTS;

CREATE TABLE HRMS.USER_GROUP
(
  ID          NUMBER,
  GROUP_NAME  VARCHAR2(50 BYTE)
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.USER_GROUP_PK ON HRMS.USER_GROUP
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.USER_GROUP ADD (
  CONSTRAINT USER_GROUP_PK
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.USER_GROUP_PK
  ENABLE VALIDATE);


DROP TABLE HRMS.USER_MENU CASCADE CONSTRAINTS;

CREATE TABLE HRMS.USER_MENU
(
  PID         NUMBER                            NOT NULL,
  PID_GROUP   NUMBER                            NOT NULL,
  PAGE_ID     NUMBER,
  PERMISSION  NUMBER(1)                         DEFAULT 1
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.C_USER_MENU_PK ON HRMS.USER_MENU
(PID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
CREATE UNIQUE INDEX HRMS.C_USER_MENU_U01 ON HRMS.USER_MENU
(PID_GROUP, PAGE_ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.USER_MENU ADD (
  CONSTRAINT C_USER_MENU_PK
  PRIMARY KEY
  (PID)
  USING INDEX HRMS.C_USER_MENU_PK
  ENABLE VALIDATE
,  CONSTRAINT C_USER_MENU_U01
  UNIQUE (PID_GROUP, PAGE_ID)
  USING INDEX HRMS.C_USER_MENU_U01
  ENABLE VALIDATE);


--  There is no statement for index HRMS.SYS_C0014922.
--  The object is created when the parent object is created.

--  There is no statement for index HRMS.SYS_C0014924.
--  The object is created when the parent object is created.

DROP SEQUENCE HRMS.DEPT_SEQ;

CREATE SEQUENCE HRMS.DEPT_SEQ
  START WITH 50
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


CREATE OR REPLACE TRIGGER HRMS.dept_trg1
              before insert ON HRMS.DEPT
              for each row
begin
                  if :new.deptno is null then
                      select dept_seq.nextval into :new.deptno from sys.dual;
                 end if;
              end;
/


DROP SEQUENCE HRMS.EMP_SEQ;

CREATE SEQUENCE HRMS.EMP_SEQ
  START WITH 8000
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


CREATE OR REPLACE TRIGGER HRMS.emp_trg1
              before insert ON HRMS.EMP
              for each row
begin
                  if :new.empno is null then
                      select emp_seq.nextval into :new.empno from sys.dual;
                 end if;
              end;
/


CREATE OR REPLACE TRIGGER HRMS.TRG_BRANCH_DEPO_PK
    BEFORE INSERT OR UPDATE
    ON HRMS.BRANCH_DEPO
    FOR EACH ROW
BEGIN
    IF :new.id IS NULL
    THEN
        SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM BRANCH_DEPO;
    END IF;
END TRG_BRANCH_DEPO_PK;
/


CREATE OR REPLACE TRIGGER HRMS.TRG_COMPANY_PK
    BEFORE INSERT OR UPDATE
    ON HRMS.COMPANY
    FOR EACH ROW
BEGIN
    IF :new.id IS NULL
    THEN
        SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM COMPANY;
    END IF;
END TRG_COMPANY_PK;
/


CREATE OR REPLACE TRIGGER HRMS.trg_desig_pk
    BEFORE INSERT OR UPDATE
    ON HRMS.DESIGNATIONS
    FOR EACH ROW
BEGIN
    IF :new.id IS NULL
    THEN
        SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM designations;
    END IF;
END trg_desig_pk;
/


CREATE OR REPLACE TRIGGER HRMS.TRG_EMPLOYEES_PK
    BEFORE INSERT OR UPDATE
    ON HRMS.EMPLOYEES
    FOR EACH ROW
BEGIN
    IF :new.id IS NULL
    THEN
        SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM employees;
    END IF;
END TRG_EMPLOYEES_PK;
/


CREATE OR REPLACE TRIGGER HRMS.trg_emp_education_pk
    BEFORE INSERT OR UPDATE
    ON HRMS.EMP_EDUCATION
    FOR EACH ROW
BEGIN
    IF :new.id IS NULL
    THEN
        SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM emp_education;
    END IF;
END trg_emp_education_pk;
/


CREATE OR REPLACE TRIGGER HRMS.TRG_EMP_EXPERIENCE_PK
    BEFORE INSERT OR UPDATE
    ON HRMS.EMP_EXPERIENCE
    FOR EACH ROW
BEGIN
    IF :new.id IS NULL
    THEN
        SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM EMP_EXPERIENCE;
    END IF;
END TRG_EMP_EXPERIENCE_PK;
/


CREATE OR REPLACE TRIGGER HRMS.TRG_EMP_FAMILY_DTL_PK
    BEFORE INSERT OR UPDATE
    ON HRMS.EMP_FAMILY_DTL
    FOR EACH ROW
BEGIN
    IF :new.id IS NULL
    THEN
        SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM EMP_FAMILY_DTL;
    END IF;
END TRG_EMP_FAMILY_DTL_PK;
/


CREATE OR REPLACE TRIGGER HRMS.TRG_EMP_GUARANTORS_PK
    BEFORE INSERT OR UPDATE
    ON HRMS.EMP_GUARANTORS
    FOR EACH ROW
BEGIN
    IF :new.id IS NULL
    THEN
        SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM EMP_GUARANTORS;
    END IF;
END TRG_EMP_GUARANTORS_PK;
/


CREATE OR REPLACE TRIGGER HRMS.TRG_EMP_NOMINEE_PK
    BEFORE INSERT OR UPDATE
    ON HRMS.EMP_NOMINEE
    FOR EACH ROW
BEGIN
    IF :new.id IS NULL
    THEN
        SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM EMP_NOMINEE;
    END IF;
END TRG_EMP_NOMINEE_PK;
/


CREATE OR REPLACE TRIGGER HRMS.TRG_EMP_TRAINING_PK
    BEFORE INSERT OR UPDATE
    ON HRMS.EMP_TRAINING
    FOR EACH ROW
BEGIN
    IF :new.id IS NULL
    THEN
        SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM EMP_TRAINING;
    END IF;
END TRG_EMP_TRAINING_PK;
/


CREATE OR REPLACE TRIGGER HRMS.TRG_LOCATIONS_PK
    BEFORE INSERT OR UPDATE
    ON HRMS.LOCATIONS
    FOR EACH ROW
BEGIN
    IF :new.id IS NULL
    THEN
        SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM LOCATIONS;
    END IF;
END TRG_LOCATIONS_PK;
/


CREATE OR REPLACE TRIGGER HRMS.TRG_UNITS_PK
    BEFORE INSERT OR UPDATE
    ON HRMS.UNITS
    FOR EACH ROW
BEGIN
    IF :new.id IS NULL
    THEN
        SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM UNITS;
    END IF;
END TRG_UNITS_PK;
/


CREATE OR REPLACE TRIGGER HRMS.T_T_Menu_Pk_Auto
    Before Insert Or Update
    ON HRMS.T_MENU
    For Each Row
Begin
    If :New.Pid Is Null
    Then
        Select Nvl (Max (Pid), 0) + 1 Into :New.Pid From T_Menu;
    End If;
End T_T_Menu_Pk_Auto;
/


ALTER TABLE HRMS.EMP ADD (
  FOREIGN KEY (MGR) 
  REFERENCES HRMS.EMP (EMPNO)
  ENABLE VALIDATE
,  FOREIGN KEY (DEPTNO) 
  REFERENCES HRMS.DEPT (DEPTNO)
  ENABLE VALIDATE);

ALTER TABLE HRMS.EMP_EDUCATION ADD (
  CONSTRAINT FK_EMP_EDUCATION 
  FOREIGN KEY (EMP_ID) 
  REFERENCES HRMS.EMPLOYEES (ID)
  ENABLE VALIDATE);

ALTER TABLE HRMS.EMP_EXPERIENCE ADD (
  CONSTRAINT FK_EMP_ID_EXPERIENCE 
  FOREIGN KEY (EMP_ID) 
  REFERENCES HRMS.EMPLOYEES (ID)
  ENABLE VALIDATE);

ALTER TABLE HRMS.EMP_FAMILY_DTL ADD (
  CONSTRAINT FK_EMP_ID_FAMILY_DTL 
  FOREIGN KEY (EMP_ID) 
  REFERENCES HRMS.EMPLOYEES (ID)
  ENABLE VALIDATE);

ALTER TABLE HRMS.EMP_GUARANTORS ADD (
  CONSTRAINT FK_EMP_ID_GUARANTORS 
  FOREIGN KEY (EMP_ID) 
  REFERENCES HRMS.EMPLOYEES (ID)
  ENABLE VALIDATE);

ALTER TABLE HRMS.EMP_NOMINEE ADD (
  CONSTRAINT FK_EMP_ID_NOMINEE 
  FOREIGN KEY (EMP_ID) 
  REFERENCES HRMS.EMPLOYEES (ID)
  ENABLE VALIDATE);

ALTER TABLE HRMS.EMP_TRAINING ADD (
  CONSTRAINT FK_EMP_ID_TRAINING 
  FOREIGN KEY (EMP_ID) 
  REFERENCES HRMS.EMPLOYEES (ID)
  ENABLE VALIDATE);

ALTER TABLE HRMS.T_MENU ADD (
  CONSTRAINT T_MENU_CON 
  FOREIGN KEY (PARENT_PID) 
  REFERENCES HRMS.T_MENU (PID)
  ENABLE VALIDATE);
