-- Create table
CREATE TABLE relations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_name VARCHAR2(50),
    relation_type VARCHAR2(20),
    sub_type VARCHAR2(20)
);

-- Insert data
-- Immediate family
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Father', 'Immediate', NULL);
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Mother', 'Immediate', NULL);
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Brother', 'Immediate', NULL);
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Sister', 'Immediate', NULL);
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Son', 'Immediate', NULL);
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Daughter', 'Immediate', NULL);
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Husband', 'Immediate', NULL);
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Wife', 'Immediate', NULL);

-- Extended family with sub-types
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Grandfather', 'Extended', 'Paternal');
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Grandfather', 'Extended', 'Maternal');
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Grandmother', 'Extended', 'Paternal');
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Grandmother', 'Extended', 'Maternal');
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Uncle', 'Extended', 'Paternal');
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Uncle', 'Extended', 'Maternal');
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Aunt', 'Extended', 'Paternal');
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Aunt', 'Extended', 'Maternal');
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Cousin', 'Extended', NULL);
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Nephew', 'Extended', NULL);
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Niece', 'Extended', NULL);

-- In-Laws
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Father-in-law', 'In-Law', NULL);
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Mother-in-law', 'In-Law', NULL);
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Brother-in-law', 'In-Law', NULL);
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Sister-in-law', 'In-Law', NULL);
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Son-in-law', 'In-Law', NULL);
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Daughter-in-law', 'In-Law', NULL);

-- Step Relations
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Stepfather', 'Step', NULL);
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Stepmother', 'Step', NULL);
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Stepson', 'Step', NULL);
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Stepdaughter', 'Step', NULL);

-- Half Relations
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Half-brother', 'Half', NULL);
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Half-sister', 'Half', NULL);

-- Godparents
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Godfather', 'Godparent', NULL);
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Godmother', 'Godparent', NULL);
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Godson', 'Godparent', NULL);
INSERT INTO relations (relation_name, relation_type, sub_type) VALUES ('Goddaughter', 'Godparent', NULL);
